"""
Django settings for crm project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os  # ← 添加这一行

# 添加这两行用于调试
print(f"BASE_DIR = {Path(__file__).resolve().parent.parent}")
print(f"TEMPLATES DIR = {Path(__file__).resolve().parent.parent / 'templates'}")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
import sys
sys.path.insert(0, BASE_DIR / 'apps')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pfx$atxo^2@%g1=7vl_2%=m2@uv0phz#m&fegxu@2^-b#niv%5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'crm.raffinato.cn',
    'www.crm.raffinato.cn',
    'raffinatocrm.onrender.com',  # Render 默认域名
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 我们的应用
    'customers',
    'templates',  # 原来的 'templates'
    'send_logs',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # 加这一行
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'crm.middleware.LoginRequiredMiddleware', 
]

ROOT_URLCONF = 'crm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # 确保这一行存在
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

import dj_database_url
import os

# 数据库配置
DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///db.sqlite3',
        conn_max_age=600,
        ssl_require=False  # Render 内部连接不需要 SSL
    )
}

# 如果是生产环境，添加这个
if not os.environ.get('DATABASE_URL'):
    # 本地开发使用 SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# 静态文件配置
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# 媒体文件配置（用于上传 Logo）
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 邮件配置（控制台输出，用于测试）
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# 登录配置
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

AUTH_USER_MODEL = 'customers.User'

# Google Gemini 配置
GEMINI_API_KEY = 'AIzaSyBLU-EpLJgZATuB6dabqBUmWdRuCO8B4lM'  # 粘贴你刚才获取的 Key

# AI配置
#OPENAI_API_KEY = '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'  # 暂未设置，后续填写
#OPENAI_API_BASE = 'https://api.openai.com/v1'
#OPENAI_MODEL = 'gpt-3.5-turbo'

# 添加 DeepSeek 配置
#OPENAI_API_KEY = 'sk-fb44df8bf89145b8ad7498b95936c699'
#OPENAI_API_BASE = 'https://api.deepseek.com/v1'
#OPENAI_MODEL = 'deepseek-chat'

SERPAPI_KEY = 'bed3f612b8d4735f9da1e4cbc7ed4e215ea625efcbfb1332a242a5004e7ae95b' # 暂未设置，后续填写

# 百度搜索配置
BAIDU_SEARCH_CONFIG = {
    'USE_PROXY': False,  # 是否使用代理
    'PROXY_LIST': [],    # 代理列表
    'USE_COOKIES': False, # 是否使用 Cookie
}

# 退信处理配置
BOUNCE_IMAP_SERVER = os.environ.get('BOUNCE_IMAP_SERVER', 'imap.qq.com')
BOUNCE_EMAIL = os.environ.get('BOUNCE_EMAIL', '')
BOUNCE_EMAIL_PASSWORD = os.environ.get('BOUNCE_EMAIL_PASSWORD', '')

# CSRF 配置
CSRF_TRUSTED_ORIGINS = [
    'https://crm.raffinato.cn',
    'https://www.crm.raffinato.cn',
    'https://raffinatocrm.onrender.com',
]

# 安全设置（HTTPS）
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Session 配置
SESSION_EXPIRE_AT_BROWSER_CLOSE = True      # 关闭浏览器即登出
SESSION_COOKIE_AGE = 3600                   # 1 小时（单位：秒）
SESSION_SAVE_EVERY_REQUEST = True           # 每次请求刷新有效期
SESSION_COOKIE_HTTPONLY = True              # 防止 XSS 偷取 Cookie