# Generated by Django 4.2.11 on 2026-04-26 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertag',
            name='assigned_sales',
        ),
        migrations.RemoveField(
            model_name='customertag',
            name='department',
        ),
        migrations.AddField(
            model_name='customer',
            name='assigned_sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to=settings.AUTH_USER_MODEL, verbose_name='负责销售'),
        ),
        migrations.AddField(
            model_name='customer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.department', verbose_name='所属部门'),
        ),
    ]
