# Generated by Django 4.2.11 on 2026-04-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customertag_assigned_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsequencequeue',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次重试时间'),
        ),
        migrations.AddField(
            model_name='emailsequencequeue',
            name='max_retries',
            field=models.IntegerField(default=3, verbose_name='最大重试次数'),
        ),
        migrations.AddField(
            model_name='emailsequencequeue',
            name='retry_count',
            field=models.IntegerField(default=0, verbose_name='已重试次数'),
        ),
    ]
