# Generated by Django 4.2.11 on 2026-04-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_emailsequencequeue_last_retry_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bounce_reason',
            field=models.TextField(blank=True, verbose_name='退信原因'),
        ),
        migrations.AddField(
            model_name='customer',
            name='bounce_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='退信类型'),
        ),
        migrations.AddField(
            model_name='customer',
            name='bounced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退信时间'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_bounced',
            field=models.BooleanField(default=False, verbose_name='邮箱已退信'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_invalid',
            field=models.BooleanField(default=False, verbose_name='邮箱无效'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email_invalid'], name='customers_email_i_0132c0_idx'),
        ),
    ]
