# Generated by Django 4.2.11 on 2026-04-27 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_bounce_reason_customer_bounce_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsubscribeBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='邮箱')),
                ('unsubscribe_reason', models.CharField(blank=True, max_length=200, verbose_name='退订原因')),
                ('unsubscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='退订时间')),
                ('unsubscribed_from', models.CharField(blank=True, max_length=100, verbose_name='退订来源')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='关联客户')),
            ],
            options={
                'verbose_name': '退订黑名单',
                'verbose_name_plural': '退订黑名单',
                'db_table': 'unsubscribe_blacklist',
                'ordering': ['-unsubscribed_at'],
            },
        ),
    ]
