# Generated by Django 4.2.11 on 2026-04-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendlog',
            name='click_count',
            field=models.IntegerField(default=0, verbose_name='点击次数'),
        ),
        migrations.AddField(
            model_name='sendlog',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='首次点击时间'),
        ),
        migrations.AddField(
            model_name='sendlog',
            name='last_click_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后点击时间'),
        ),
        migrations.AddField(
            model_name='sendlog',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='首次打开时间'),
        ),
    ]
