# Generated by Django 4.2.11 on 2026-04-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_logs', '0002_sendlog_click_count_sendlog_clicked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendlog',
            name='bounce_reason',
            field=models.TextField(blank=True, verbose_name='退信原因'),
        ),
        migrations.AddField(
            model_name='sendlog',
            name='bounce_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='退信类型'),
        ),
        migrations.AddField(
            model_name='sendlog',
            name='is_bounced',
            field=models.BooleanField(default=False, verbose_name='是否退信'),
        ),
    ]
